-- Обычные слова из файла АВП
INSERT OR IGNORE INTO UltraWords (value, typeId, partOfSpeechId, isDeclinable, link, comment, DateTimeSaving, Popularity)
SELECT
    value,
    (SELECT Id FROM Types WHERE Value = 'Общий') AS typeId,
    (SELECT Id FROM PartsOfSpeech WHERE Value = partOfSpeech) AS partOfSpeechId,
    1 AS isDeclinable,
    link,
    'Православие' AS comment,
    datetime('now', 'localtime') AS DateTimeSaving,
    0 AS Popularity
FROM (
    -- ============ СУЩЕСТВИТЕЛЬНЫЕ ============
    SELECT 'Абзац' AS value, 'Существительное' AS partOfSpeech, 'https://azbyka.ru/otechnik/Feofan_Zatvornik/redaktorskaja-pravka-svjatitelem-feofanom-zatvornikom-vyshenskim-svoih-rukopisej-dlja-izdanija-v-pechat/' AS link UNION ALL
    SELECT 'Абсолют', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-duhovnogo-i-idealnogo-v-otnoshenijah-boga-i-cheloveka-po-tvorenijam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Автограф', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sobranie-pisem-iz-neopublikovannogo/' UNION ALL
    SELECT 'Авторитет', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Агент', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/epistoljarnoe-nasledie-svjatitelja-feofana-zatvornika-narrativ-i-obraz-avtora/' UNION ALL
    SELECT 'Агнец', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Агония', 'Существительное', 'https://azbyka.ru/otechnik/Silvestr_Olshevskij/delatel-bezukoriznennyj-tom-1/' UNION ALL
    SELECT 'Ад', 'Существительное', 'https://azbyka.ru/otechnik/Silvestr_Olshevskij/delatel-bezukoriznennyj-tom-1/' UNION ALL
    SELECT 'Администратор', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Адрес', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Азбука', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bez-truda-ne-spaseshsja/' UNION ALL
    SELECT 'Акафист', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Академия', 'Существительное', 'https://azbyka.ru/otechnik/Istorija_Tserkvi/russkie-pisateli-bogoslovy/2_85' UNION ALL
    SELECT 'Акцент', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/uchenie-svjatitelja-feofana-zatvornika-o-hristianskom-podvige/' UNION ALL
    SELECT 'Аллегория', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Алтарь', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Алфавит', 'Существительное', 'https://azbyka.ru/otechnik/Silvestr_Olshevskij/delatel-bezukoriznennyj-tom-1/' UNION ALL
    SELECT 'Амвон', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/rech-skazannaja-pri-pogrebenii-ep-feofana-12-janvarja-1894-g/' UNION ALL
    SELECT 'Амулет', 'Существительное', 'https://azbyka.ru/otechnik/Ioann_Zlatoust/' UNION ALL
    SELECT 'Аналой', 'Существительное', 'https://azbyka.ru/otechnik/Varsonofij_Optinskij/prepodobnyj-varsonofij-optinskij-o-podvige-zatvora-svjatitelja-feofana/' UNION ALL
    SELECT 'Анафема', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Ангел', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Англичанин', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/Pisma-o-raznykh-predmetakh-very-i-zhizni/' UNION ALL
    SELECT 'Ангелология', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bogoslovskie-vozzrenija-svt-feofana-zatvornika-na-prirodu-angelov-i-chelovecheskoj-dushi/' UNION ALL
    SELECT 'Апокалипсис', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tolkovanie-na-poslanie-k-evrejam/' UNION ALL
    SELECT 'Апостол', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tolkovanie-poslanij-apostola-pavla-v-dorevolyutsionnoj-traditsii-russkoj-pravoslavnoj-tserkvi/' UNION ALL
    SELECT 'Аргумент', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/novozavetnaja-ekklesiologija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Архиерей', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gody-prepodavanija-svjatitelja-feofana-govorova-v-sankt-peterburgskoj-duhovnoj-akademii/' UNION ALL
    SELECT 'Архимандрит', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/slova-s-peterburgskoj-duhovnoj-akademii-rektora-arhimandrita-feofana/' UNION ALL
    SELECT 'Аскет', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Аскетика', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/kratkij-ocherk-asketiki-kak-vklad-svt-feofana-zatvornika-v-russkuyu-shkolu-bogoslovija/' UNION ALL
    SELECT 'Аудитория', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Афон', 'Существительное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/miterikon-kak-perevod-svjatitelja-feofana-issledovanija-i-perspektivy/' UNION ALL

    -- ============ ГЛАГОЛЫ (инфинитив) ============
    SELECT 'Адаптировать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/miterikon-kak-perevod-svjatitelja-feofana-issledovanija-i-perspektivy/' UNION ALL
    SELECT 'Акцентировать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/redaktorskaja-pravka-svjatitelem-feofanom-zatvornikom-vyshenskim-svoih-rukopisej-dlja-izdanija-v-pechat/' UNION ALL
    SELECT 'Анализировать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/uchenie-svjatitelja-feofana-zatvornika-o-hristianskom-podvige/' UNION ALL
    SELECT 'Благословить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Вдохновлять', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Верить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Видеть', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Воспитывать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/hristianskoe-vospitanie-po-ucheniyu-sv-feofana-zatvornika/' UNION ALL
    SELECT 'Восходить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Вразумлять', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Говорить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Грешить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Действовать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/protsess-duhovnogo-hristianskogo-sovershenstvovanija-po-izobrazheniyu-episkopa-feofana/' UNION ALL
    SELECT 'Думать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Желать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Жить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tsel-zhizni-hristianina-i-puti-ego-podviga-po-pismam-svjatitelja-feofana-zatvornika-k-mirjanam/' UNION ALL
    SELECT 'Заботиться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Знать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Изучать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/ekzegetika-i-duhovnaja-zhizn-svjatitel-feofan-kak-tolkovatel-psalmov/' UNION ALL
    SELECT 'Искать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Исповедовать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Каяться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/chto-potrebno-pokajavshemusja-i-vstupivshemu-na-dobryj-put-spasenija/' UNION ALL
    SELECT 'Любить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Молиться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-molitve/' UNION ALL
    SELECT 'Мыслить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Надеяться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Наставлять', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/nastavlenija-v-duhovnoj-zhizni/' UNION ALL
    SELECT 'Обращаться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Объяснять', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Ожидать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Освящать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/svjatoe-prichastie-v-zhitii-i-uchenii-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Осуществлять', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-duhovnogo-i-idealnogo-v-otnoshenijah-boga-i-cheloveka-po-tvorenijam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Отвергать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Отвечать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Открывать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/letopis-zhizni-i-tvorenij-svjatitelja-feofana-zatvornika-vyshenskogo-1859-1863-tom-2/' UNION ALL
    SELECT 'Писать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Показывать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Понимать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-otkrytija-novogo-znanija-v-trudah-svt-feofana-zatvornika/' UNION ALL
    SELECT 'Причащаться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/svjatoe-prichastie-v-zhitii-i-uchenii-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Проповедовать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Радоваться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Рассуждать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Служить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sluzhenie-svjatitelja-feofana-inspektorom-novgorodskoj-duhovnoj-seminarii/' UNION ALL
    SELECT 'Слышать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Совершать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/protsess-duhovnogo-hristianskogo-sovershenstvovanija-po-izobrazheniyu-episkopa-feofana/' UNION ALL
    SELECT 'Спасаться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bez-truda-ne-spaseshsja/' UNION ALL
    SELECT 'Стараться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Стремиться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tsel-zhizni-hristianina-i-puti-ego-podviga-po-pismam-svjatitelja-feofana-zatvornika-k-mirjanam/' UNION ALL
    SELECT 'Творить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Убеждать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Углубляться', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/uchenie-ob-iisusovoj-molitve-po-trudam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Уповать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Учить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/nastavlenija-v-duhovnoj-zhizni/' UNION ALL
    SELECT 'Хранить', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gospod-poslal-k-tebe-nuzhdajushhegosja/' UNION ALL
    SELECT 'Целовать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sbornik-slov-i-propovedej-o-nashem-otnoshenii-k-khramam/' UNION ALL
    SELECT 'Читать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Чувствовать', 'Глагол', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-duhovnogo-i-idealnogo-v-otnoshenijah-boga-i-cheloveka-po-tvorenijam-svjatitelja-feofana-zatvornika/' UNION ALL

    -- ============ ПРИЛАГАТЕЛЬНЫЕ ============
    SELECT 'Абсолютный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/antropologija-svjatitelja-feofana-zatvornika-i-zarozhdenie-pervyh-personalisticheskih-kontseptsij-v-russkom-bogoslovii/' UNION ALL
    SELECT 'Автономный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/kievskaja-bogoslovskaja-shkola-svjatitel-feofan-zatvornik-i-p-d-yurkevich/' UNION ALL
    SELECT 'Актуальный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/novozavetnaja-ekklesiologija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Ангельский', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gospod-poslal-k-tebe-nuzhdajushhegosja/' UNION ALL
    SELECT 'Безгрешный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Безмолвный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Бесконечный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-duhovnogo-i-idealnogo-v-otnoshenijah-boga-i-cheloveka-po-tvorenijam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Благодатный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Божественный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bozhestvennaja-blagodat-i-svoboda-cheloveka/' UNION ALL
    SELECT 'Вечный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Греховный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Духовный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Живой', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Земной', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Истинный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Ложный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Молитвенный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-molitve/' UNION ALL
    SELECT 'Мудрый', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Небесный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Нравственный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Пастырский', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pastyrskoe-dushepopechenie-po-pismam-episkopa-feofana-govorova/' UNION ALL
    SELECT 'Праведный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Священный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/svjashhennoe-pisanie-po-tvorenijam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Совершенный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/protsess-duhovnogo-hristianskogo-sovershenstvovanija-po-izobrazheniyu-episkopa-feofana/' UNION ALL
    SELECT 'Спасительный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bez-truda-ne-spaseshsja/' UNION ALL
    SELECT 'Тайный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Церковный', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tolkovanie-poslanij-apostola-pavla-v-dorevolyutsionnoj-traditsii-russkoj-pravoslavnoj-tserkvi/' UNION ALL
    SELECT 'Человеческий', 'Прилагательное', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/antropologija-svjatitelja-feofana-zatvornika-i-zarozhdenie-pervyh-personalisticheskih-kontseptsij-v-russkom-bogoslovii/' UNION ALL

    -- ============ НАРЕЧИЯ ============
    SELECT 'Абсолютно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/uchenie-svjatitelja-feofana-zatvornika-o-tsennosti-duhovnoj-zhizni-kak-vyzov-vremeni-rossijskomu-obshhestvu-19-v/' UNION ALL
    SELECT 'Аккуратно', 'Наречие', 'https://azbyka.ru/otechnik/Silvestr_Olshevskij/delatel-bezukoriznennyj-tom-1/' UNION ALL
    SELECT 'Активно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/mnenie-svjatitelja-feofana-zatvornika-o-protestantizme/' UNION ALL
    SELECT 'Безмолвно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Благочестиво', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Вдумчиво', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Верно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Вообще', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Всецело', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tsel-zhizni-hristianina-i-puti-ego-podviga-po-pismam-svjatitelja-feofana-zatvornika-k-mirjanam/' UNION ALL
    SELECT 'Высоко', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Глубоко', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/uchenie-ob-iisusovoj-molitve-po-trudam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Горячо', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Действительно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Духовно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/uchenie-svjatitelja-feofana-zatvornika-o-tsennosti-duhovnoj-zhizni-kak-vyzov-vremeni-rossijskomu-obshhestvu-19-v/' UNION ALL
    SELECT 'Естественно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/antropologija-svjatitelja-feofana-zatvornika-i-zarozhdenie-pervyh-personalisticheskih-kontseptsij-v-russkom-bogoslovii/' UNION ALL
    SELECT 'Живо', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Истинно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Искренне', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Кротко', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Медленно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/redaktorskaja-pravka-svjatitelem-feofanom-zatvornikom-vyshenskim-svoih-rukopisej-dlja-izdanija-v-pechat/' UNION ALL
    SELECT 'Молитвенно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-molitve/' UNION ALL
    SELECT 'Мудро', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Навсегда', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Напрасно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Настойчиво', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Непременно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bez-truda-ne-spaseshsja/' UNION ALL
    SELECT 'Осторожно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/redaktorskaja-pravka-svjatitelem-feofanom-zatvornikom-vyshenskim-svoih-rukopisej-dlja-izdanija-v-pechat/' UNION ALL
    SELECT 'Открыто', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/novozavetnaja-ekklesiologija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Очевидно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Правильно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Постоянно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Праведно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Прилежно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bez-truda-ne-spaseshsja/' UNION ALL
    SELECT 'Прямо', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Радостно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Свято', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Смиренно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Совершенно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/protsess-duhovnogo-hristianskogo-sovershenstvovanija-po-izobrazheniyu-episkopa-feofana/' UNION ALL
    SELECT 'Тайно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Твёрдо', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/volevye-kachestva-lichnosti-ih-vospitanie-soglasno-svjatitelyu-feofanu-zatvorniku-v-perspektive-sovremennoj-obrazovatelnoj-paradigmy/' UNION ALL
    SELECT 'Тихо', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Тщательно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/redaktorskaja-pravka-svjatitelem-feofanom-zatvornikom-vyshenskim-svoih-rukopisej-dlja-izdanija-v-pechat/' UNION ALL
    SELECT 'Убеждённо', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Уверенно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/volevye-kachestva-lichnosti-ih-vospitanie-soglasno-svjatitelyu-feofanu-zatvorniku-v-perspektive-sovremennoj-obrazovatelnoj-paradigmy/' UNION ALL
    SELECT 'Чисто', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Явно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Ясно', 'Наречие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL

    -- ============ ДЕЕПРИЧАСТИЯ ============
    SELECT 'Адаптируя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/miterikon-kak-perevod-svjatitelja-feofana-issledovanija-i-perspektivy/' UNION ALL
    SELECT 'Анализируя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/molitvennaja-praktika-mirskogo-cheloveka-v-epistoljarnom-nasledii-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Веря', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Видя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Говоря', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Действуя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/protsess-duhovnogo-hristianskogo-sovershenstvovanija-po-izobrazheniyu-episkopa-feofana/' UNION ALL
    SELECT 'Думая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Желая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Живя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tsel-zhizni-hristianina-i-puti-ego-podviga-po-pismam-svjatitelja-feofana-zatvornika-k-mirjanam/' UNION ALL
    SELECT 'Зная', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Изучая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/ekzegetika-i-duhovnaja-zhizn-svjatitel-feofan-kak-tolkovatel-psalmov/' UNION ALL
    SELECT 'Имея', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Исповедуя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Каясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/chto-potrebno-pokajavshemusja-i-vstupivshemu-na-dobryj-put-spasenija/' UNION ALL
    SELECT 'Любя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Молясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-molitve/' UNION ALL
    SELECT 'Мысля', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Надеясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Обращаясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Объясняя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Ожидая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Освящая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/svjatoe-prichastie-v-zhitii-i-uchenii-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Осуществляя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-duhovnogo-i-idealnogo-v-otnoshenijah-boga-i-cheloveka-po-tvorenijam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Отвергая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Отвечая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Открывая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/letopis-zhizni-i-tvorenij-svjatitelja-feofana-zatvornika-vyshenskogo-1859-1863-tom-2/' UNION ALL
    SELECT 'Пиша', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Показывая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Понимая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-otkrytija-novogo-znanija-v-trudah-svt-feofana-zatvornika/' UNION ALL
    SELECT 'Причащаясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/svjatoe-prichastie-v-zhitii-i-uchenii-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Проповедуя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Радуясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Рассуждая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Служа', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sluzhenie-svjatitelja-feofana-inspektorom-novgorodskoj-duhovnoj-seminarii/' UNION ALL
    SELECT 'Слыша', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Совершая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/protsess-duhovnogo-hristianskogo-sovershenstvovanija-po-izobrazheniyu-episkopa-feofana/' UNION ALL
    SELECT 'Спасаясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bez-truda-ne-spaseshsja/' UNION ALL
    SELECT 'Стараясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Стремясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tsel-zhizni-hristianina-i-puti-ego-podviga-po-pismam-svjatitelja-feofana-zatvornika-k-mirjanam/' UNION ALL
    SELECT 'Творя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Убеждая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Углубляясь', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/uchenie-ob-iisusovoj-molitve-po-trudam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Уповая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Уча', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/nastavlenija-v-duhovnoj-zhizni/' UNION ALL
    SELECT 'Храня', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gospod-poslal-k-tebe-nuzhdajushhegosja/' UNION ALL
    SELECT 'Целуя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sbornik-slov-i-propovedej-o-nashem-otnoshenii-k-khramam/' UNION ALL
    SELECT 'Читая', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Чувствуя', 'Деепричастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-duhovnogo-i-idealnogo-v-otnoshenijah-boga-i-cheloveka-po-tvorenijam-svjatitelja-feofana-zatvornika/' UNION ALL

    -- ============ ПРИЧАСТИЯ ============
    SELECT 'Адаптированный', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/miterikon-kak-perevod-svjatitelja-feofana-issledovanija-i-perspektivy/' UNION ALL
    SELECT 'Вдохновляющий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Говорящий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Действующий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/protsess-duhovnogo-hristianskogo-sovershenstvovanija-po-izobrazheniyu-episkopa-feofana/' UNION ALL
    SELECT 'Живущий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tsel-zhizni-hristianina-i-puti-ego-podviga-po-pismam-svjatitelja-feofana-zatvornika-k-mirjanam/' UNION ALL
    SELECT 'Знающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Изучающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/ekzegetika-i-duhovnaja-zhizn-svjatitel-feofan-kak-tolkovatel-psalmov/' UNION ALL
    SELECT 'Ищущий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Любящий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Молящийся', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-molitve/' UNION ALL
    SELECT 'Мыслящий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Надеющийся', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Обращающийся', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Объясняющий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Ожидающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Освящающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/svjatoe-prichastie-v-zhitii-i-uchenii-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Отвергающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/o-pravoslavii-s-predosterezhenijami-ot-pogreshenij-protiv-nego/' UNION ALL
    SELECT 'Отвечающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Открывающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/letopis-zhizni-i-tvorenij-svjatitelja-feofana-zatvornika-vyshenskogo-1859-1863-tom-2/' UNION ALL
    SELECT 'Пишущий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Понимающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-otkrytija-novogo-znanija-v-trudah-svt-feofana-zatvornika/' UNION ALL
    SELECT 'Проповедующий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gomileticheskoe-nasledie-svjatitelja-feofana-zatvornika-vyshenskogo/' UNION ALL
    SELECT 'Радующийся', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Рассуждающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Служащий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sluzhenie-svjatitelja-feofana-inspektorom-novgorodskoj-duhovnoj-seminarii/' UNION ALL
    SELECT 'Слышащий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Совершающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/protsess-duhovnogo-hristianskogo-sovershenstvovanija-po-izobrazheniyu-episkopa-feofana/' UNION ALL
    SELECT 'Спасающийся', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/bez-truda-ne-spaseshsja/' UNION ALL
    SELECT 'Старающийся', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Стремящийся', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/tsel-zhizni-hristianina-i-puti-ego-podviga-po-pismam-svjatitelja-feofana-zatvornika-k-mirjanam/' UNION ALL
    SELECT 'Творящий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/sozertsanie-i-razmyshlenie/' UNION ALL
    SELECT 'Убеждающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gnoseologicheskie-i-sotsialnye-predposylki-nravstvennogo-uchenija-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Углубляющийся', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/uchenie-ob-iisusovoj-molitve-po-trudam-svjatitelja-feofana-zatvornika/' UNION ALL
    SELECT 'Уповающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma-o-duhovnoj-zhizni/' UNION ALL
    SELECT 'Учащий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/nastavlenija-v-duhovnoj-zhizni/' UNION ALL
    SELECT 'Хранящий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/gospod-poslal-k-tebe-nuzhdajushhegosja/' UNION ALL
    SELECT 'Читающий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/pisma/' UNION ALL
    SELECT 'Чувствующий', 'Причастие', 'https://azbyka.ru/otechnik/Feofan_Zatvornik/problema-duhovnogo-i-idealnogo-v-otnoshenijah-boga-i-cheloveka-po-tvorenijam-svjatitelja-feofana-zatvornika/' UNION ALL
);